### PR TITLE
Decrease the size of the GitHub icon in the details page

### LINKED ISSUE #19: The Github image link is huge
It should be smaller

image

### PR DESCRIPTION
**Pull request by arnav-t**
## Changes
- Reduce the size of the GitHub icon to `2em`
- Align the icon along with the card header text

image
Fixes #19

### CODE REVIEW

**Review by jkutner — APPROVED** [review]

**Review by elbandito — APPROVED** [review]
Nice work on adjusting the image size.  

In the issue we also spoke about replacing the image with a NON specific github image, because these homepage URLs are not guaranteed to be specific to github.  That being said.  I fine to approve this and open a new issue for replacing the image.

**Comment by arnav-t** [comment]
@elbandito Sure, do we just want a generic link icon for every URL, or do we want to parse the URL and then determine which icon to display?

**Comment by arnav-t** [comment]
@jkutner @elbandito 
The homepage link icon would now be different for GitHub links and a generic link.
GitHub
Generic

**Comment by jkutner** [comment]
@arnav-t looks great!

**Pull request merged**
